{% set name = "MicroED data" %}
{% set tarname = name|lower|replace(' ', '-') %}
{% set urlname = tarname|replace('data', 'tools') %}
{% set version = "0.1.0-dev.8" %}

package:
  name: {{ tarname }}
  version: {{ version|replace('-dev.', '.dev') }}

source:
  url: https://cryoem.ucla.edu/downloads/{{ urlname }}-{{ version }}.tar.gz
  sha256: 5fe6677f5d1f5eedfd50b8436b4c36918d1d7d4f1ad3da28b71a132ea9d19cb6

build:
  noarch: generic
  number: 0

requirements:
  build:
    - coreutils     # [unix]
    - m2-coreutils  # [win]

test:
  commands:
    - test -d "${PREFIX}/share/${PKG_NAME}"              # [unix]
    - if not exist "%PREFIX%\share\%PKG_NAME%\\" exit 1  # [win]

about:
  home: https://cryoem.ucla.edu/microed
  license: ISC
  license_file: LICENSE
  summary: "Test data for the MicroED tools"

extra:
  recipe-maintainers:
    - hattne
