{% set name = "MicroED data" %}
{% set tarname = name|lower|replace(' ', '-') %}
{% set urlname = tarname|replace('data', 'tools') %}
{% set version = "0.1.0-dev.9" %}

package:
  name: {{ tarname }}
  version: {{ version|replace('-dev.', '.dev') }}

source:
  url: https://cryoem.ucla.edu/downloads/{{ urlname }}-{{ version }}.tar.gz
  sha256: 804edd2bdb1db740ebf1abe660f6a0ee26b8b2a28f50c523bfbda5817718b2f7

build:
  noarch: generic
  number: 0

requirements:
  build:
    - coreutils     # [unix]
    - m2-coreutils  # [win]

test:
  commands:
    - test -d "${PREFIX}/share/${PKG_NAME}"              # [unix]
    - if not exist "%PREFIX%\share\%PKG_NAME%\\" exit 1  # [win]

about:
  home: https://cryoem.ucla.edu/microed
  license: ISC
  license_file: LICENSE
  summary: "Test data for the MicroED tools"

extra:
  recipe-maintainers:
    - hattne
